### ISSUE TITLE
Wrong PHP constraint (composer.json claims PHP 5.3 is supported, however ::class constant is used)

### ISSUE THREAD

**Issue by Nemrtvej** [vihuvac/recaptcha-bundle#14]
Hello, I am using version 2.1.6. In composer.json, there is a requirement for         `"php": "^5.3 || ^7.0"`
however, in class `Vihuvac\Bundle\RecaptchaBundle\Form\Type\VihuvacRecaptchaType` in method `getParent` ([line 140](https://github.com/vihuvac/recaptcha-bundle/blob/v2.1.6/Form/Type/VihuvacRecaptchaType.php#L140))  there is a call `TextType::class`.

`::class` according to http://php.net/manual/en/language.oop5.constants.php, the ::class constant was added in PHP 5.5.

Would it be possible to sync PHP constraint with the actual code?

**Comment by vihuvac** [comment]
@Nemrtvej Apologise for the delay, the aim is to preserve the support of **Symfony** version from **2.3** and **higher**. The bundle does not depends on just the PHP version, but also depends on the requirements for each Symfony version.

Technically you are right about the small point but maybe you forgot there are users using the previous versions of **Symfony**, **PHP** and the **Recaptcha Bundle**.

I think we must preserver the compatibility as much as we can!

I pushed a small hotfix (**v2.1.7**) in order to make the bundle work without any problem.

Thanks a lot for writing.

**Comment by Nemrtvej** [comment]
Hello @vihuvac, I am not sure if we understand eachother correctly :).

My point is, that your [composer.json claims](https://github.com/vihuvac/recaptcha-bundle/blob/master/composer.json#L21), that it is PHP 5.3 compatible. However, in [this line of code](https://github.com/vihuvac/recaptcha-bundle/blob/master/Form/Type/VihuvacRecaptchaType.php#L140) you are using PHP language feature available from PHP 5.5 and forth. Therefore, your bundle is not PHP 5.3 compatible. 

To be honest, I don't know how to properly replace the `::class` call. I am just pointing out that version 2.1.7 is still not fixing this problem and it is still not compatible with PHP 5.3/5.4 :-).

Personally, I fixed this for myself by using [cweagans/composer-patches](https://github.com/cweagans/composer-patches) and using this patchfile:

```
--- /dev/null
+++ recaptcha-bundle/Form/Type/VihuvacRecaptchaType.php
@@ -137,7 +137,7 @@
      */
     public function getParent()
     {
-        return TextType::class ? "form" : "text";
+        return 'form';
     }

     /**
```

I am well aware that this is not a proper future-proof solution, I am just mentioning it for future reference or if somebody will have same problem as me.

Nevertheless, thank you for your response and good work on this bundle ;-).

**Comment by vihuvac** [comment]
@Nemrtvej I understand about what you are talking about, technically it may be right if you talk about a feature reduced to just PHP, but its a Symfony feature (form feature) based on the minimal PHP requirement so if your PHP version is equal or higher than 5.5 then you'll be using ```TextType::class``` otherwise you are using ```"text"``` (text field).

Take a look at the [Symfony Form Types](http://api.symfony.com/2.3/Symfony/Component/Form/Extension/Core/Type/TextType.html). The ```TextType``` is a **String** like ```CheckboxType```.

Your fix ```return 'form';``` is technically the same! In **Symfony 2.3** the ```FormType``` is a **String** as well!

Docs for creating a custom field type in Symfony 2.3 are not currently available, but its similar to [How to Create a Custom Form Field Type in Symfony 2.7](http://symfony.com/doc/2.7/form/create_custom_field_type.html#creating-a-template-for-the-field).

There's not need for you to use another one bundle in order to fix this because it's not necessary! In case you want to overwrite or perform a deep customisation you may overwrite any part of a bundle, there's an official doc provided by Symfony.

I hope the links help to clarify your doubt.

Thanks a lot for writing.

**Comment by Nemrtvej** [comment]
@vihuvac well, yes, your call TextType::class returns string "TextType" (or something like that, maybe with FQDN). 
But the problem is that when I try to run your code on PHP 5.3/5.4, I get Syntax Error. The PHP itself cannot parse the code. It cannot handle the `TextType::class` at all. The parser consider it as a garbage and the execution fails. No Symfony starts at all. 

You are talking about compatibility with Symfony, I am talking about 
```
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /in/KMXvd on line 5

Process exited with code 255.
```

Have a look at https://3v4l.org/KMXvd - Output for 5.4.0 - 5.4.45  - And your composer.json claims those version are supported by your bundle.

**Comment by vihuvac** [comment]
@Nemrtvej umm I'm for sure you got something wrong in your settings! If you are using PHP versions under 5.5 you must use the bundle like that:

```php
<?php

...

public function buildForm(FormBuilder $builder, array $options)
{
    // ...
    $builder->add("recaptcha", "vihuvac_recaptcha");
    // ...
}

...
```

The bundle tests ran successfully with the last update, I'm currently using the bundle with Symfony versions from 2.3 till 3.2.7 and PHP versions from 5.3 till 7.0 believe me!

Just in case, retake a look at the README file because it was updated as well!

If the problem persist show me how you are using the bundle or for better reference you can add a test case, it'd be awesome!
